sudo: false
language: C
services:
  - docker

cache:
    directories:
      - $HOME/.cache

env:
    global:
      - PRODUCT=tarantool-expirationd
    matrix:
      - TARGET=test VERSION=1_10
      - TARGET=test VERSION=2x
      - TARGET=test VERSION=2_2
      - OS=el DIST=6
      - OS=el DIST=7
      - OS=fedora DIST=28
      - OS=fedora DIST=29
      - OS=fedora DIST=30
      - OS=ubuntu DIST=trusty
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=bionic
      - OS=ubuntu DIST=cosmic
      - OS=ubuntu DIST=disco
      - OS=debian DIST=jessie
      - OS=debian DIST=stretch
      - OS=debian DIST=buster

script:
  - git describe --long
  - |
    if [ "${TARGET}" = "test" ]; then
        ./test.sh;
    else
        git clone https://github.com/packpack/packpack.git packpack;
        packpack/packpack;
    fi;

before_deploy:
  - ls -l build/

deploy:
  # Deploy packages to PackageCloud
  - provider: packagecloud
    username: tarantool
    repository: "1_10"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}" && "${TRAVIS_EVENT_TYPE}" != 'cron'

  - provider: packagecloud
    username: tarantool
    repository: "2x"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}" && "${TRAVIS_EVENT_TYPE}" != 'cron'

  - provider: packagecloud
    username: tarantool
    repository: "2_2"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      branch: master
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}" && "${TRAVIS_EVENT_TYPE}" != 'cron'
  # Archive packages
  # - provider: script
  #   script: ./travis-archive.sh modules
  #   on:
  #     branch: master
  #     condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}" && "${TRAVIS_EVENT_TYPE}" != 'cron'

notifications:
  email:
    recipients:
      - build@tarantool.org
    on_success: change
    on_failure: always
